### ISSUE TITLE
To do by week

### ISSUE THREAD

**Issue by mvantieghem** [ijd2109/mastersThesis#1]
- Structural - 
		○ Need to send him the list of stuff to include 
		○ With and without structural 
	- Functional 
		○ All of different forests had different hyperparameters 
		○ Best tree is variance explained, instead of RMSE 
		○ Something weird with bootstrap samples where the first few are really good, and should be random --> Ian should look into this 
	- Big picture: random forest 
		○ How well are we performing with predictions?
		○ Plots of  structure vs. functional
			§ the RMSE
			§ R2  
			§ Generate ROC curves: sensitivity vs. specificity 
		○ Out of bag is not good enough - need cross-validated or hold-out 20% and bootstrap 
	- Start with age, 
		○ Long term we will do age, CBCL, group classification

**Comment by pab2163** [comment]
Intro:
-P1: Machine learning + prediction can help dev science. Not just explain, but a prediction can help -- explaining variance in the real world. A caveat of balancing interpretability with predictive power. 
-P2: Why random forests have been powerful in balancing interpretation with predictive performance 
-P3: Highlight a few instances of RF in dev psych/neuro to show it has promise. Linear vs. nonlinear relationships
-P4: Here, we show some ways in which RF can be a good tool for balancing prediction and interpretation in developmental psych. One critique of ML is that TONS of data are needed -- here we show the degree of effectiveness of RF techniques on moderately-sized datasets (plus missing data)

Methods:
--Participants -- SB, first brain scan, etc
--MRI task/scan info from https://pbloom.shinyapps.io/longitudinalamyggrowth/
--Structural scan info from Michelle sending email
--Functional preproc -- regress out 24 motion parameters, then taking BOLD timecourses averaged across every Harvard-Oxford ROI, making correlation matrix for every subject
--Random Forests --- for now, keep it simple. Don't try to include too much. For each of the three outcomes -- 1 basic model from structural, 1 form functional. 

Results:
--3 Figures, one for each outcome (CBCL, Age, Group)
--In each figure, show model performance OOB and variable importance for 2 models (model 1 = structural, model 2 = functional)

Discussion:
-Interpret it!



Other:
-For paper, knit markdown as PDF


YAY!

**Comment by pab2163** [comment]
For next week:
-Forget age / CBCL, just write up group
-NO ANALYSIS! (for your own sake!)
-Have a draft of the paper (okay if stuff is missing, methods /results most important)
-Without doing analysis, try to get github up to date
-Don't do analysis!

**Comment by ijd2109** [comment]
done
